### ISSUE TITLE
Add additional commit message type "deps" to categorize dependency updates

### ISSUE THREAD

**Issue by sspaink** [influxdata/validate-semantic-github-messages#17]
The Telegraf project has a lot of dependencies, therefore we get a lot of pull requests that update the dependencies (such as this one https://github.com/influxdata/telegraf/pull/11266) and we are reporting these in the [changelog in a separate section](https://github.com/influxdata/telegraf/blob/master/CHANGELOG.md#dependency-updates). I was hoping to find a way to categorize these types of pull requests so when we generate the changelog it gets sorted automatically. 

@jacobmarble and @tysonkamp What do you think about extending the support "types" (e.g. feat,fix) to include something like "deps"? This definitely isn't a blocker, I think there are other approaches we can take, but curious to hear your thoughts on this possibility?

**Comment by tysonkamp** [comment]
I'm fine with it, but I am no opinionated regarding commit messages.  @jacobmarble  I defer to you and other dev managers and dev teams. Thoughts?

**Comment by domodwyer** [comment]
For what it's worth, dependabot opens PRs tagged as [`chore(deps)`](https://github.com/influxdata/influxdb_iox/pulls?q=is%3Apr+chore%28deps%29) which might be worth using for consistency with the automated stuff :+1:

**Comment by sspaink** [comment]
I didn't know dependabot already had a convention with `chore(deps)`, we can definitely work with that for automation. Thank you!
