### ISSUE TITLE
Support exclamation mark as breaking change notation 

### ISSUE THREAD

**Issue by sspaink** [influxdata/validate-semantic-github-messages#19]
The semantic checker doesn't seem to support using the exclamation mark for breaking changes: https://github.com/influxdata/telegraf/pull/11748, I would like this feature to be supported. I assume the regex pattern just needs to be updated https://github.com/influxdata/validate-semantic-github-messages/blob/main/semantic_pattern.txt ?

From https://www.conventionalcommits.org/en/v1.0.0/
```
BREAKING CHANGE: a commit that has a footer BREAKING CHANGE:, or appends a ! after the type/scope, introduces a breaking API change (correlating with [MAJOR](http://semver.org/#summary) in Semantic Versioning). A BREAKING CHANGE can be part of commits of any type.
```

**Comment by domodwyer** [comment]
I too missed this - I would welcome it! It's part of the spec, and useful information to get across.

I prefer it to the `BREAKING CHANGE:` footer as it shows up in `git log --oneline` 👍
